# Generated by Django 4.1.3 on 2022-11-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.TextField()),
                ("image", models.TextField()),
                ("click", models.TextField()),
                ("conv", models.TextField()),
            ],
        ),
    ]
