# Generated by Django 4.1.3 on 2022-12-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_rename_click_feed_explain_feed_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='detail',
            field=models.TextField(default='aa'),
        ),
    ]
