# Generated by Django 4.1.3 on 2022-12-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_feed_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='address',
            field=models.TextField(default='aa'),
        ),
    ]
